### ISSUE TITLE
Sony Music Player Magisk Crashing In Android 6.0.1 CM13

### ISSUE THREAD

**Issue by ghost** [Manish4586/Sony_Music-Magisk#1]
![Screenshot_20200117-140301](https://user-images.githubusercontent.com/37603562/72588191-7dcdaa80-3932-11ea-85d3-d146d85d4082.png)
![Screenshot_20200117-140318](https://user-images.githubusercontent.com/37603562/72588209-8920d600-3932-11ea-991e-2ad44d40927a.png)
### Crash Log
[SemcMusicPlayer.txt](https://github.com/Manish4586/Sony_Music-Magisk/files/4075290/SemcMusicPlayer.txt)
### Phone Specs
Mali-450 GPU
MT6592
Magisk v20.3
Magisk Manager v7.5.1

**Comment by Manish4586** [comment]
Okk thanks for the info.
Try updating it from playstore.
Switch to 7.1.2

**Comment by Manish4586** [comment]
Kindly update it from playstore

**Comment by ghost** [comment]
Still crashing after updating the music player :(
![Screenshot_20200117-174933](https://user-images.githubusercontent.com/37603562/72602191-d19bbc00-3951-11ea-991e-88d12db5c929.png)
![Screenshot_20200117-174927](https://user-images.githubusercontent.com/37603562/72602203-d82a3380-3951-11ea-8c25-5a252a71c784.png)

**Comment by Manish4586** [comment]
Okk i will update it

**Comment by ghost** [comment]
It's ok now but I downgraded from this version 😅
![Screenshot_20200121-164041](https://user-images.githubusercontent.com/37603562/72788399-d4a5ed80-3c6c-11ea-9fcb-8a789934f770.png)
